insert_test:
    path: /feeds/insert-test
    defaults: { _controller: AppBundle:Feed:insertTest }

feeds_list:
    path: /feeds/index
    defaults: { _controller: AppBundle:Feed:index }

edit_feed:
    path: /feeds/edit/{id}
    defaults: { _controller: AppBundle:Feed:edit, id:id }
    methods: [GET]

create_feed:
    path: /feeds/create
    defaults: { _controller: AppBundle:Feed:edit }
